package io.lucky.security.domain

object LogAction {
    const val CREATE_ORDER = "createOrder"
    const val PUBLISH_OUTBOX = "publishOutbox"
    const val ORDER_VALIDATED = "orderValidated"
    const val ORDER_REJECTED = "orderRejected"
    const val SUBMIT_ORDER = "submitOrder"
    const val CONSUME_VALIDATED = "consumeValidated"
    const val CONSUME_VALIDATED_FAILED = "consumeValidatedFailed"
    const val CONSUME_REJECTED = "consumeRejected"
    const val CONSUME_REJECTED_FAILED = "consumeRejectedFailed"
    const val SIMULATE_VALIDATED = "simulateValidated"
    const val SIMULATE_REJECTED = "simulateRejected"
    const val APPLY_EXECUTION = "applyExecution"
    const val CONSUME_EXECUTION = "consumeExecution"
    const val CONSUME_EXECUTION_FAILED = "consumeExecutionFailed"
    const val SIMULATE_EXECUTION = "simulateExecution"
    const val REQUEST_CANCEL = "requestCancel"
    const val ORDER_CANCELLED = "orderCancelled"
    const val CONSUME_CANCEL_CONFIRMED = "consumeCancelConfirmed"
    const val CONSUME_CANCEL_CONFIRMED_FAILED = "consumeCancelConfirmedFailed"
    const val SIMULATE_CANCEL_CONFIRMED = "simulateCancelConfirmed"
    const val EXECUTION_SKIPPED_CANCELLED = "executionSkippedCancelled"
    const val EXECUTION_SKIPPED_DUPLICATE = "executionSkippedDuplicate"
    const val CANCEL_SKIPPED_DUPLICATE = "cancelSkippedDuplicate"
    const val APPLY_EXECUTION_BATCH = "applyExecutionBatch"
    const val CONSUME_EXECUTION_BATCH = "consumeExecutionBatch"
    const val SYNC_FILLED_QTY = "syncFilledQuantity"
    const val LOCK_ACQUIRE_FAILED = "lockAcquireFailed"
}
