CREATE DATABASE orchestrator;
GRANT ALL PRIVILEGES ON DATABASE orchestrator TO study;

CREATE DATABASE security;
GRANT ALL PRIVILEGES ON DATABASE security TO study;

CREATE DATABASE bff;
GRANT ALL PRIVILEGES ON DATABASE bff TO study;
