spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5438/security
    username: study
    password: study
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5678
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    cache:
      channel:
        size: 50
  data:
    redis:
      host: localhost
      port: 6378
